name: CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone DDK
      run: |
        git clone https://github.com/SebastianSzturo/Dictionary-Development-Kit.git "$HOME"/'Dictionary Development Kit'
    - name: Clone Warodai
      run: |
        git clone --depth=1 https://github.com/warodai/warodai-source.git "$HOME"/'warodai-source'
    - name: Transform Warodai to Apple dictionary XML
      run: |
        ./make-dict-xml.py "$HOME"/'warodai-source' > warodai.xml
    - name: Prepare plist file
      run: |
        cat Warodai.plist.in | m4 -DYEAR=$(date +%Y) -DVERSION_DATE=$(date +%Y.%m.%d) > Warodai.plist
    - name: Build dictionary
      run: |
        make
    - name: Package dictionary
      run: |
        mkdir pkgdir
        cp -R objects/*.dictionary pkgdir
        hdiutil create tmp.dmg -ov -volname "Warodai" -fs HFS+ -srcfolder "./pkgdir"
        hdiutil convert tmp.dmg -format UDZO -o Warodai.dmg
    - name: Cleanup
      run: |
        make clean
        rm -rf pkgdir
        rm tmp.dmg
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.date.outputs.date }}
        artifacts: ./Warodai.dmg
        artifactContentType: application/x-apple-diskimage
        token: ${{ secrets.GITHUB_TOKEN }}
